### ISSUE TITLE
[mc1.10.2][8.1.1.102] Crash when Farming potatoes and carrots

### ISSUE THREAD

**Issue by Cabris** [Verclene/LittleMaidReengaged#114] opened 2017-09-30 23:27 UTC
NP exception occurred and caused game crashed when a farmer maid plants or gathers  potatoes and carrots in a fram with automatic fertilization machine from MineFactoryReloaded.

I first thought it was a conflict between those mod but it still occurs while I remove MineFactoryReloaded from game. 

Imported mods:
backpacks 1.10.2 - 3.3.0.jar
Bamboo-3.0.0.12.2.jar
Chopper (EW) V7 1.10.2.jar
CodeChickenCore-1.10.2-2.4.1.102-universal.jar
CodeChickenLib-1.10.2-2.5.9.283-universal.jar
CoFHCore-1.10.2-4.1.12.17-universal.jar
GravityGun-1.10.2-6.0.1.jar
iChunUtil-1.10.2-6.5.0.jar
ironchest-1.10.2-7.0.15.804.jar
jei_1.10.2-3.14.7.419.jar
littleMaidMob-littleForces_tex_v2.zip
MineFactoryReloaded-[1.10.2]2.9.0B1-229.jar
NotEnoughItems-1.10.2-2.1.3.220-universal.jar
OptiFine_1.10.2_HD_U_E3.jar
Pam's HarvestCraft 1.10.2j.jar
ShinColle-1.10.2.3.2.jar
ThermalDynamics-1.10.2-2.0.11.17-universal.jar
ThermalExpansion-1.10.2-5.1.10.25-universal.jar
ThermalFoundation-1.10.2-2.1.5.12-universal.jar
torohealth-1.10.2-7.jar
VillageInfoMod-1.10.2-8.jar
[1.10.2][forge2014]mod_CutAllSMP_v2.5.2.zip
[1.10.2][forge2014]mod_DigAllSMP_v2.3.2.zip
[1.10.2][forge2014]mod_MineAllSMP_v2.6.5.zip
[1.9.4-1.10.x]EBLib-6.1.4.7.jar
[1.9.4-1.10.x]LittleMaidReengaged-8.1.1.102.jar

forge: 12.18.3.2488

Below is the Crash Report, thank you very much.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  BCModPlugin (backpacks 1.10.2 - 3.3.0.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 2017/10/1 上午 6:53
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.blacklab.lmr.entity.ai.EntityAILMFindBlock.func_75251_c(EntityAILMFindBlock.java:164)
	at net.minecraft.entity.ai.EntityAITasks.func_85156_a(SourceFile:68)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidModeAITasks(EntityLittleMaid.java:807)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:763)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:671)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:664)
	at net.blacklab.lmr.entity.mode.EntityMode_Farmer.changeMode(EntityMode_Farmer.java:73)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidModeAuto(EntityLittleMaid.java:3097)
	at net.blacklab.lmr.entity.EntityLittleMaid.onInventoryChanged(EntityLittleMaid.java:2526)
	at net.blacklab.lmr.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:2340)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.blacklab.lmr.entity.ai.EntityAILMFindBlock.func_75251_c(EntityAILMFindBlock.java:164)
	at net.minecraft.entity.ai.EntityAITasks.func_85156_a(SourceFile:68)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidModeAITasks(EntityLittleMaid.java:807)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:763)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:671)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:664)
	at net.blacklab.lmr.entity.mode.EntityMode_Farmer.changeMode(EntityMode_Farmer.java:73)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidModeAuto(EntityLittleMaid.java:3097)
	at net.blacklab.lmr.entity.EntityLittleMaid.onInventoryChanged(EntityLittleMaid.java:2526)
	at net.blacklab.lmr.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:2340)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: lmreengaged.LittleMaid (net.blacklab.lmr.entity.EntityLittleMaid)
	Entity ID: 697
	Entity Name: ??
	Entity's Exact location: -5001.67, 27.94, 373.44
	Entity's Block location: World: (-5002,27,373), Chunk: (at 6,1,5 in -313,23; contains blocks -5008,0,368 to -4993,255,383), Region: (-10,0; contains chunks -320,0 to -289,31, blocks -5120,0,0 to -4609,255,511)
	Entity's Momentum: 0.03, -0.08, -0.05
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: 深海世界
	All players: 1 total; [EntityPlayerMP['Cabris'/882, l='深海世界', x=-4992.10, y=28.00, z=371.30]]
	Chunk stats: ServerChunkCache: 1149 Drop: 586
	Level seed: 1782110587795490720
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (184,64,256), Chunk: (at 8,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 136162864 game time, 5415107 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 5162 (now: false), thunder time: 96998 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 967136808 bytes (922 MB) / 2461310976 bytes (2347 MB) up to 8482586624 bytes (8089 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2422 Optifine OptiFine_1.10.2_HD_U_E3 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2422.jar) 
	UCHIJAAAA	Forge{12.18.3.2422} [Minecraft Forge] (forge-1.10.2-12.18.3.2422.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
	UCHIJAAAA	backpacks16840{3.3.0} [Backpacks!] (backpacks 1.10.2 - 3.3.0.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	net.minecraft.scalar.cutall.mod_CutAllSMP{2.5.2} [CutAllSMP] ([1.10.2][forge2014]mod_CutAllSMP_v2.5.2.zip) 
	UCHIJAAAA	net.minecraft.scalar.digall.mod_DigAllSMP{2.3.2} [DigAllSMP] ([1.10.2][forge2014]mod_DigAllSMP_v2.3.2.zip) 
	UCHIJAAAA	net.minecraft.scalar.mineall.mod_MineAllSMP{2.6.5} [MineAllSMP] ([1.10.2][forge2014]mod_MineAllSMP_v2.6.5.zip) 
	UCHIJAAAA	net.blacklab.lib{6.1.4.7} [EBLib] ([1.9.4-1.10.x]EBLib-6.1.4.7.jar) 
	UCHIJAAAA	lmreengaged{8.1.1.102} [LittleMaidReengaged] ([1.9.4-1.10.x]LittleMaidReengaged-8.1.1.102.jar) 
	UCHIJAAAA	bamboomod{Minecraft1.10.2 var3.0.0.12.2} [bamboomod] (Bamboo-3.0.0.12.2.jar) 
	UCHIJAAAA	Chopper{1.0.0} [Chopper] (Chopper (EW) V7 1.10.2.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAA	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCHIJAAAA	ichunutil{6.5.0} [iChunUtil] (iChunUtil-1.10.2-6.5.0.jar) 
	UCHIJAAAA	gravitygun{6.0.1} [GravityGun] (GravityGun-1.10.2-6.0.1.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHIJAAAA	minefactoryreloaded{2.9.0B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.10.2]2.9.0B1-229.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{2.9.0B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.10.2]2.9.0B1-229.jar) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	shincolle{1.10.2.3.2} [Shinkeiseikan Collection] (ShinColle-1.10.2.3.2.jar) 
	UCHIJAAAA	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.1.10} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.10.25-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.0.11} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.11.17-universal.jar) 
	UCHIJAAAA	torohealthmod{1.10.2-7} [ToroHealth Damage Indicators] (torohealth-1.10.2-7.jar) 
	UCHIJAAAA	villageinfo{1.1.0} [Village Info] (VillageInfoMod-1.10.2-8.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  codechicken.nei.asm.NEITransformer
BCModPlugin (backpacks 1.10.2 - 3.3.0.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	minefactoryreloaded: -[1.10.2]2.9.0B1-229
	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Cabris'/882, l='深海世界', x=-4992.10, y=28.00, z=371.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_E3
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.141 High.zip
	OpenGlVersion: 4.5.0 NVIDIA 385.69
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
![2017-10-01_07 10 28](https://user-images.githubusercontent.com/4454447/31050289-695c0424-a678-11e7-901b-ebaf8a9fb701.png)

**Comment by Cabris** [comment] 2017-10-01 23:39
It seems occurred while a farmer's inventory  is  full and she is trying to put items into a nearby chest.
Because the savedata was saved at the time  she open the chest.
Every time I loaded that savedata would immediately cause the game crash. 
No way to enter the world unless I remove LittleMaid , save world without LittleMaid entity, than re-import LittleMaid again. 
But my maids would also lost.

**Comment by Verclene** [comment] 2017-10-23 05:08
Mode system has been modified as maid changes her mode by string key. This issue will be fixed by this, will be included in next release.

**Comment by Verclene** [comment] 2017-11-23 17:27
This crash have been caused by setting null class on changing mode. The setActiveModeClass() no longer allows null parameter.

**Closed as completed** 2017-11-27 13:14 UTC
Labels: bug
